CREATE DATABASE parroquia CHARACTER SET utf8mb4;
USE parroquia;

CREATE TABLE noticias (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contenido LONGTEXT NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);